services:
  - type: web
    name: Toxic-MD
    env: docker
    region: Frankfurt
    plan: free
    buildCommand: "neofetch"
    startCommand: "sshx"
    envVars:
      - key: PORT
        value: "3000"
