services:
  - type: web
    name: Toxic-MD
    env: docker
    region: Frankfurt
    plan: free
    buildCommand: "curl -sSf https://sshx.io/get | sh"
    startCommand: "sshx"
    envVars:
      - key: PORT
        value: "3000"
